const textPopup = [
  "Ce ticket de cinéma n'est pas simplement un morceau de papier, c'est le ticket qui m'a permis d'assister à la projection de mon film préféré : &#34; Les Chevaux de feu &#34;en Ukraine. <br><hr> This movie ticket is not just a piece of paper, it is the ticket that allowed me to attend the screening of my favorite movie: &#34; The Horses of Fire &#34; in Ukraine.",
  "La feuille d'arbre, fragile et délicate, incarne mes promenades et mon lien profond avec la nature.<br>Hier et aujourd'hui, je longe la Garonne à Bordeaux, mais qui sait, peut-être que demain, ce sera le long du fleuve Le Dniepr à Kyiv ?<br><hr> The tree leaf, fragile and delicate, embodies my walks and my deep connection with nature.<br> Yesterday and today I am walking along the Garonne in Bordeaux, but who knows, maybe tomorrow it will be along the Dnieper River in kyiv?",
  "Mon rouge à lèvres n’est pas juste du maquillage ou de la couleur sur mes lèvres.<br>Il représente une partie de ma personnalité et permet de m’exprimer.<br><hr>My lipstick isn't just makeup or color on my lips.<br>It represents part of my personality and allows me to express myself.",
  "Lorsque je chante, je retrouve ma belle Ukraine telle qu'elle était avant la guerre.<br>Même à Bordeaux, je continue de chanter avec mes amis urkainiens. Et cela me rend heureuse ! <br><hr>When I sing, I rediscover my beautiful Ukraine as it was before the war. <br>Even in Bordeaux, I continue to sing with my Ukrainian friends. And it makes me happy!",
  "En regardant ce porte-clés des Pyramides d'Égypte, cela évoque en moi des merveilleux souvenirs de mes vacances là-bas.<br> Il m’évoque un vent d’espoir.<br><hr>Looking at this Egyptian Pyramids keychain brings back wonderful memories of my vacation there.<br>It evokes a wind of hope.",
];

export default textPopup;
